[[redirects]]
  from = "/articles/2024-08-19-hello-world"
  to = "/articles/hello-world-introducing-planship"
  status = 301

[[redirects]]
  from = "/articles/2024-09-26-naming-is-hard"
  to = "/articles/naming-things-is-hard-saas-pricing-nomenclature-edition"
  status = 301
